#include <termios.h>

// Function to initialize the keyboard
void init_keyboard(){
  
 
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock # v
}
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #
    // # i like cock #